# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.0"
manifest_format = "2.0"
project_hash = "f8de100613d7b0992c324206239b56c0ad1f3c05"

[[deps.ZoneProfilers]]
path = "."
uuid = "402d8ed9-92af-47cb-aae4-ae215e44b74b"
version = "0.1.0"
