name = "ZoneProfilers"
uuid = "402d8ed9-92af-47cb-aae4-ae215e44b74b"
version = "0.1.1"
authors = ["Nathan Zimmerberg <nzimmerberg@gmail.com>"]

[workspace]
projects = ["test"]

[compat]
julia = "1.10"
